#!/usr/bin/env bash
GIT_MANAGE_FILE="${HOME}"/.git_manage

function _git_manage_add()
{
    for repo in "$@"; do
        repo_dir=$(cd "${repo}" && pwd)
        if [ -d "${repo_dir}"/.git ]; then
            if ! grep "^${repo_dir}$" "${GIT_MANAGE_FILE}" > /dev/null; then
                echo "${repo_dir}" >> "${GIT_MANAGE_FILE}"
            fi
        else
            echo "${repo_dir}" is not a git repository
        fi
    done
}

if [ $# -eq 0 ]; then
    _git_manage_add `pwd`
else
    _git_manage_add "$@"
fi
