#!/usr/bin/env bash
case "$1" in
    "add")
        shift
        exec git-manage-add "$@"
        ;;
    "remove")
        shift
        exec git-manage-remove "$@"
        ;;
    "ls")
        exec git-manage-ls
        ;;
    "lookover")
        exec git-manage-lookover
        ;;
    "pull")
        shift
        exec git-manage-pull "$@"
        ;;
    *)
        echo 'Usage: git manage [add|remove|ls|lookover|pull]'
        ;;
esac
