#!/usr/bin/env bash
GIT_MANAGE_FILE="${HOME}"/.git_manage

function _exclude_repo_from_manage_file()
{
    if grep "^$1$" "${GIT_MANAGE_FILE}" > /dev/null; then
        sed -i -e "\|^$1$|d" "${GIT_MANAGE_FILE}"
    else
        printf '%s' "$1 is not a managed repo"
    fi
}

function _git_manage_remove()
{
    for repo in "$@"; do
        repo_dir=$(cd "${repo}" && pwd)
        if [ -d "${repo_dir}"/.git ]; then
            _exclude_repo_from_manage_file "${repo_dir}"
        else
            echo "${repo_dir}" is not a git repository
        fi
    done
}

function _git_manage_remove_interactive()
{
    IFS=$'\n' repos=`cat "${GIT_MANAGE_FILE}" | fzf --multi`
    for repo in ${repos}; do
        _exclude_repo_from_manage_file "${repo}"
    done
}

function show_usage()
{
    printf '%s\n\t%b\n' "git manage remove [repo1 repo2..]"\
        "Exclude specified repos from managed repos.\
        \n\tIf no repos are specified, the current directory will be excluded."
    printf '%s\n\t%b\n' "git manage remove -i"\
        "Intaractively select repos with fzf to exclude from managed repos.\
        \n\tSelect repos with tab key, then press enter to remove them"
}

if [ $# -eq 0 ]; then
    _git_manage_remove `pwd`
else
    case "$1" in
        "-h"|"--help")
            show_usage
            ;;
        "-i")
            _git_manage_remove_interactive
            ;;
        *)
            _git_manage_remove "$@"
            ;;
    esac
fi
