#!/usr/bin/env bash
GIT_MANAGE_FILE="${HOME}"/.git_manage

function _git_manage_remove()
{
    for repo in "$@"; do
        repo_dir=$(cd "${repo}" && pwd)
        if [ -d "${repo_dir}"/.git ]; then
            if grep "^${repo_dir}$" "${GIT_MANAGE_FILE}" > /dev/null; then
                sed -i -e "\|^${repo_dir}$|d" "${GIT_MANAGE_FILE}"
            fi
        else
            echo "${repo_dir}" is not a git repository
        fi
    done
}

function _git_manage_remove_interactive()
{
    IFS=$'\n' repos=`cat "${GIT_MANAGE_FILE}" | fzf --multi`
    _git_manage_remove ${repos}
}

function show_usage()
{
    printf '%s\n\t%b\n' "git manage remove [repo1 repo2..]"\
        "Exclude specified repos from managed repos.\
        \n\tIf no repos are specified, the current directory will be excluded."
    printf '%s\n\t%b\n' "git manage remove -i"\
        "Intaractively select repos with fzf to exclude from managed repos.\
        \n\tSelect repos with tab key, then press enter to remove them"
}

if [ $# -eq 0 ]; then
    _git_manage_remove `pwd`
else
    case "$1" in
        "-h"|"--help")
            show_usage
            ;;
        "-i")
            _git_manage_remove_interactive
            ;;
        *)
            _git_manage_remove "$@"
            ;;
    esac
fi
