#!/usr/bin/env python3
import argparse, os, re, glob
parser = argparse.ArgumentParser(description='Trim "temp" from beginning of file name(s)')
parser.add_argument('input', nargs='*', metavar='input_file',
                    help='Input file name(s). If omitted, all files in the current directory are passed into the script')

args = parser.parse_args()

# Regular expressoin matching for temp_ or temp- at the beginning of file names
pattern = re.compile(r'^temp(_|-)+')

files = args.input
if len(files) == 0:
    files = glob.iglob('temp*')
    # files = os.listdir('./')    # all files and directory
    files = [item for item in files if os.path.isfile(item)]

for a_file in files:
    if os.path.isfile(a_file):
        basename = os.path.basename(a_file)
        new_name = pattern.sub('', basename)
        os.replace(basename, new_name)
    
# while files:
#     a_file = files.pop(0)
#     basename = os.path.basename(a_file)
#     new_name = pattern.sub('', basename)
#     os.replace(basename, new_name)

